title: "Rightstar Computer Tr. LLC"
email: "info@rightstarcomputer.com"
description: "Trust us. We can make it"

baseurl: ""
url: ""
repository: "Rightstar2023/rightstarcomputer.github.io"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

---
layout: home
---



