title: Right Star Computer
url: https://rightstarcomputer.com
baseurl: ""

repository: "Rightstar2023/rightstarcomputer.github.io"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

---
layout: home
title: Right Star Computer
---



