# Basic site settings
title: "Rightstar Computer Tr. LLC"
email: "info@rightstarcomputer.com"
description: "Personal website for Rightstar Computer"
# baseurl is the subpath of your site, e.g. "/repo-name". Leave empty for user/organization sites.
baseurl: ""
# url is the full URL of your site. Leave empty to use GitHub Pages default.
url: ""
repository: "Rightstar2023/rightstarcomputer.github.io"

# Theme and plugins
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

# Markdown and permalinks
markdown: kramdown
permalink: /:categories/:title/

# Pagination
paginate: 5

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Files and directories to exclude from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
