title: "Rightstar Computer Tr. LLC"
email: "info@rightstarcomputer.com"
description: "Website for Rightstar Computer"
baseurl: ""
url: ""
repository: "Rightstar2023/rightstarcomputer.github.io"
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown
permalink: /:categories/:title/

paginate: 5

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

